services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - backend-net
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend-net
  hairism-backend-app:
    image: hairism-backend-app
    container_name: hairism-backend-app-container
    depends_on:
      - elasticsearch
      - redis
    ports:
      - "1271:1271"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
