services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - backend-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend-net
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend-net
  hairism-backend-app:
    build: .
    container_name: hairism-backend-app-container
    depends_on:
      - elasticsearch
      - redis
    ports:
      - "127.0.0.1:1271:1271"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
